version: '3'

services:
  datanode:
    image: onbehalfofme/dfs-datanode:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    volumes:
      -  /:/home/ubuntu


