version: '3'

services:
  datanode:
    image: onbehalfofme/dfs_namenode:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      -  /:/home/ubuntu


